apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techtrends-staging 
  namespace: argocd
spec:
template:
    metadata:
      annotations:
        kubernetes.io/change-cause: "Restarting pods"
        restart-timestamp: 1
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values-staging.yaml
    path: project/helm
    repoURL: https://github.com/upanitag/nd064_course_1
    targetRevision: HEAD
