## file location and name: # .github/workflows/techtrends-dockerhub.yml

##  Named of the workflow.
name: Tech Trends - Package with Docker
## Set the trigger policy.
## In this case, the workflow is execute on a `push` event,
## or when a new commit is pushed to main
on: 
  push:
    branches:
      - main # Trigger the workflow on pushes to the main branch
## List the steps to be executed by the workflow
jobs:
  ## Set the name of the job
  techtrends:
    ## Configure the operating system the workflow should run on.
    ## In this case, the job on Ubuntu
    runs-on: ubuntu-latest
    ## Define a sequence of steps to be executed 
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ../../Dockerfile
          platforms: linux/amd64
          push: true
          tags: upanitag/techtrends:latest
