namespace:
  name: prod

service:
  port: 7111

image:
  pullpolicy: Always

replicaCount: 5

# Uncomment and adjust resource requests and limits as needed
# resources:
#   requests:
#     memory: 128Mi
#     cpu: 350m
#   limits:
#     memory: 256Mi
#     cpu: 500m
